# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 16:21
from __future__ import unicode_literals

import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_add_homepage_preview_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                ]
            ),
        ),
    ]
