# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_collectionpage'),
        ('pages', '0004_contentpage_body_streamfield'),
    ]

    operations = [
    ]
