# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 22:16
from __future__ import unicode_literals

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_merge_20181116_1144"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional. Brief description for preview display. Will also be used for search description without tags, if none is entered",
            ),
        ),
    ]
