# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_content_page_image_caption_footnotes'),
        ('pages', '0008_contributor_page'),
    ]

    operations = [
    ]
