# Generated by Django 4.0.10 on 2023-09-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_new_richtext_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="orcid",
            field=models.URLField(
                blank=True,
                help_text="ORCID url, if available, to include in "
                + "editorial author citation",
                max_length=255,
                verbose_name="ORCID iD",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="project_years",
            field=models.CharField(
                blank=True,
                help_text="Project years, if desired for display on contributor list.",
                max_length=255,
            ),
        ),
    ]
