exclude_patterns:
- "**/node_modules/"
- "**/settings/**"
- "ppa/archive/management/commands/check_hathi_excerpts.py"
- "ppa/archive/management/commands/import_clusters.py"
- "*.config.js"
- "*.conf.js"
- "sitemedia/semantic/"
- "docs/"
- "**/test/"
- "**/tests/"
- "**/tests.py"
- "**/migrations/"