language: python

python:
  - "3.6"

env:
  global:
    - SOLR_VERSION=6.6.0
    - SOLR_CORE=test-ppa

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py ppa/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> ppa/local_settings.py

before_script:
  - SOLR_VERSION=$SOLR_VERSION SOLR_CORE=$SOLR_CORE bash ci/config_solr.sh


script:
  - py.test --cov=ppa

sevices:
  - mysql

after_success:
  - codecov
