- name: Run database migrations
  django_manage:
    command: migrate
    app_path: "{{ deploy }}"
    virtualenv: "{{ deploy }}/env"
- name: Check for current symlink as previous
  stat:
    path: "{{ install_root }}/current"
  register: previous
- name: Set current symlink
  file:
    src: "{{ deploy }}"
    dest: "{{ install_root }}/current"
    state: link
- name: Register current symlink
  stat:
    path: "{{ install_root }}/current"
  register: current
- name: If current path differs from previous current, update previous
  file:
    src: "{{ previous.stat.lnk_target }}"
    dest: "{{ install_root }}/previous"
    state: link
  when: previous.stat.exists == True and previous.stat.lnk_source != current.stat.lnk_source
- name: Register there is now a previous symlink
  stat:
    path: "{{ install_root }}/previous"
  register: previous
- name: If previous did not exist (and therefore wasn't reset above), create it with current
  # should only trigger on first run of deploy script
  file:
    src: "{{ deploy }}"
    dest: "{{ install_root }}/previous"
    state: link
  when: previous.stat.exists == False
- name: Set /var/www/ path to make live
  file:
    src: "{{ deploy }}"
    dest: "/var/www/{{ symlink }}"
    state: link
- name: Call restorecon just in case
  shell: '/usr/sbin/restorecon -R {{ install_root }}'
  args:
    warn: False
    executable: /bin/bash
- name: Restart Apache (scl-httpd24-httpd)
  command: "sudo systemctl restart httpd24-httpd"
