- hosts: '{{ group | default("qa") }}'
  connection: '{{ conn | default("local") }}'
  remote_user: deploy
  # Set environment to use scl rh-python35
  environment:
    PATH: '{{ remote_path }}'
    LD_LIBRARY_PATH: '{{ remote_ld }}'
    PYTHONPATH: '{{ remote_python }}'
  roles:
      # Creates repo variable names and builds repo
      - projectrepo
      # Builds a production deploy and sets file permissions correctly
      - buildprod
      # Makes an emergency database backup, run migrations, and then resets
      # symlinks
      - golive
