# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('enumcron', models.CharField(max_length=255, null=True, verbose_name='Enumeration/Chronology')),
                ('author', models.CharField(max_length=255)),
                ('pub_place', models.CharField(max_length=255, verbose_name='Place of Publication')),
                ('pub_date', models.CharField(max_length=255, verbose_name='Publication Date')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
