# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-15 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_digitizedwork_add_record_id"),
        ("archive", "0005_add_notes_fields"),
    ]

    operations = []
