# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_merge_20181015_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='digitizedwork',
            options={'ordering': ('sort_title',)},
        ),
        migrations.AddField(
            model_name='collection',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Exclude by default on public search.'),
        ),
        migrations.AlterField(
            model_name='digitizedwork',
            name='public_notes',
            field=models.TextField(blank=True, default='', help_text='Notes on edition or other details (displayed on public site)'),
        ),
        migrations.AlterField(
            model_name='digitizedwork',
            name='sort_title',
            field=models.TextField(default='', help_text='Sort title from MARC record'),
        ),
    ]
