# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_collection_add_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizedwork',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('S', 'Suppressed')], default='P', help_text='Changing status to suppressed will remove rsync data for that volume and remove from the public index. This is currently not reversible; use with caution.', max_length=2),
        ),
    ]
