# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_add_protected_fields'),
        ('archive', '0011_remove_publisher_character_limit'),
    ]

    operations = [
    ]
