# Generated by Django 2.2.19 on 2021-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0014_add_source_option_gale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitizedwork",
            name="enumcron",
            field=models.CharField(
                blank=True,
                help_text="Enumcron for HathiTrust material; volume for Gale material",
                max_length=255,
                verbose_name="Enumeration/Chronology/Volume",
            ),
        ),
        migrations.AlterField(
            model_name="digitizedwork",
            name="record_id",
            field=models.CharField(
                blank=True,
                help_text="For HathiTrust materials, record id (use to aggregate copies or volumes); for Gale materials, ESTC id.",
                max_length=255,
            ),
        ),
    ]
