# Generated by Django 3.2.14 on 2022-08-17 21:10

import django.db.models.deletion
from django.db import migrations, models

import ppa.archive.models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0017_digitizedwork_uniquetogether_sourceid_pagerange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_id",
                    models.CharField(
                        help_text="Unique identifier for a cluster of digitized works",
                        max_length=255,
                        unique=True,
                        verbose_name="Cluster ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="digitizedwork",
            name="pages_digital",
            field=models.CharField(
                blank=True,
                help_text="Sequence of pages in the digital edition. Use full digits for start and end separated by a dash (##-##); for multiple sequences, separate ranges by a comma (##-##, ##-##). NOTE: removing page range may have unexpected results.",
                max_length=255,
                validators=[ppa.archive.models.validate_page_range],
                verbose_name="Page range (digital edition)",
            ),
        ),
        migrations.AddField(
            model_name="digitizedwork",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archive.cluster",
            ),
        ),
    ]
