# Generated by Django 3.2.16 on 2023-03-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_add_clusters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ('cluster_id',)},
        ),
    ]
