# Generated by Django 5.0.2 on 2024-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0019_alter_cluster_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitizedwork",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Automatically calculated on import; recalculated on save when digital page range changes",
                null=True,
            ),
        ),
    ]
