# Generated by Django 5.0.2 on 2024-03-25 18:52

import ppa.archive.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0020_digitizedwork_page_count_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitizedwork",
            name="protected_fields",
            field=ppa.archive.models.ProtectedWorkField(
                blank=True,
                default=ppa.archive.models.ProtectedWorkFieldFlags,
                help_text="Fields protected from HathiTrust bulk update because they have been manually edited in the Django admin.",
            ),
        ),
    ]
