# Generated by Django 5.0.2 on 2024-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0021_alter_digitizedwork_protected_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitizedwork",
            name="old_workid",
            field=models.CharField(
                blank=True,
                help_text="past work id; used for excerpts previously identified by start of digital page range",
                max_length=255,
                verbose_name="Old Work ID",
            ),
        ),
    ]
