# Generated by Django 5.0.2 on 2024-04-04 13:26

from django.db import migrations

from intspan import intspan


def populate_excerpt_old_workid(apps, schema_editor):
    DigitizedWork = apps.get_model("archive", "DigitizedWork")
    # find all works with a digital page range
    for digwork in DigitizedWork.objects.exclude(pages_digital=""):
        # use logic similar to model code to parse the page range
        # and get the number of the first page
        first_digital_page = list(intspan(digwork.pages_digital))[0]
        # should not be possible to save a record with a page range
        # that can't be parsed by intspan
        # previously, excerpt id was source_id-pN where N is first digital page
        digwork.old_workid = f"{digwork.source_id}-p{first_digital_page}"
        digwork.save()


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0022_digitizedwork_old_workid"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_excerpt_old_workid, reverse_code=migrations.RunPython.noop
        )
    ]
