# Generated by Django 5.0.2 on 2024-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0023_save_excerpt_old_workid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="digitizedwork",
            constraint=models.UniqueConstraint(
                fields=("source_id", "pages_orig"), name="unique_sourceid_pages_orig"
            ),
        ),
    ]
