# Generated by Django 5.0.2 on 2024-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0024_digitizedwork_unique_sourceid_pages_orig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitizedwork",
            name="source",
            field=models.CharField(
                choices=[
                    ("HT", "HathiTrust"),
                    ("G", "Gale"),
                    ("E", "EEBO-TCP"),
                    ("O", "Other"),
                ],
                default="HT",
                help_text="Source of the record.",
                max_length=2,
            ),
        ),
    ]
