# Generated by Django 5.2 on 2025-06-11 21:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0025_add_eebotcp_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("HT", "HathiTrust"),
                            ("G", "Gale"),
                            ("E", "EEBO-TCP"),
                            ("O", "Other"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    wagtail.fields.RichTextField(
                        help_text="A brief note to appear next to the source name in search results, as a tooltip"
                    ),
                ),
            ],
        ),
    ]
