# Generated by Django 5.2.14 on 2026-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_sourcenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='adapter_name',
            field=models.CharField(blank=True, default='', help_text='Name of the adapter to use for works in this collection (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='list_view_fields',
            field=models.JSONField(blank=True, help_text='Custom fields to display in list view (JSON array). Leave empty to use adapter defaults.', null=True),
        ),
        migrations.AddField(
            model_name='digitizedwork',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
