# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 21:57
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("paragraph", wagtail.core.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                ]
            ),
        ),
    ]
