# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0002_editorialpage_body_streamfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorialpage",
            name="date",
        ),
    ]
