# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 22:26
from __future__ import unicode_literals

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editorial", "0003_remove_editorialpage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional. Brief description for preview display. Will also be used for search description (without tags), if one is not entered.",
            ),
        ),
    ]
