# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:32
from __future__ import unicode_literals

import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations

import ppa.pages.models


class Migration(migrations.Migration):
    dependencies = [
        ("editorial", "0004_editorialpage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="authors",
            field=wagtail.fields.StreamField(
                [
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            ppa.pages.models.Person
                        ),
                    )
                ],
                blank=True,
                help_text="Optional. Brief description for preview display. Will also be used for search description without tags, if none is entered",
            ),
        ),
    ]
