# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:32
from __future__ import unicode_literals

from django.db import migrations
import ppa.pages.models
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_editorialpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.snippets.blocks.SnippetChooserBlock(ppa.pages.models.Person))], blank=True, help_text='Select people snippets to add as authors. Use the plus sign to add as many as you like. Drag and drop to order.'),
        ),
    ]
