# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import ppa.editorial.models
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_editorialpage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.snippets.blocks.SnippetChooserBlock(ppa.editorial.models.Person))], blank=True),
        ),
    ]
