# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-20 14:42
from __future__ import unicode_literals

from django.db import migrations
import ppa.pages.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0005_add_person_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialpage",
            name="authors",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            ppa.pages.models.Person
                        ),
                    )
                ],
                blank=True,
                help_text="Select or create people snippets to add as authors.",
            ),
        ),
        migrations.AlterField(
            model_name="editorialpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.core.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "document",
                            ]
                        ),
                    ),
                    (
                        "captioned_image",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_text",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"],
                                        required=False,
                                    ),
                                ),
                                (
                                    "style",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full", "Full Width"),
                                            ("left", "Floated Left"),
                                            ("right", "Floated Right"),
                                        ],
                                        help_text="Controls how other content flows around the image. Note         that this will only take effect on larger screens. Float consecutive         images in opposite directions for side-by-side display.",
                                    ),
                                ),
                            ],
                            label="image",
                        ),
                    ),
                    (
                        "footnotes",
                        wagtail.core.blocks.RichTextBlock(
                            classname="footnotes",
                            features=["ol", "ul", "bold", "italic", "link"],
                        ),
                    ),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                ]
            ),
        ),
    ]
