# Generated by Django 3.2.14 on 2023-09-01 15:00

import django.core.validators
from django.db import migrations, models
import ppa.pages.models
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("editorial", "0008_new_richtext_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialpage",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier (DOI) if registered, "
                + "in short form",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DOI in short form, starting with 10.",
                        regex="^10[.][0-9]{4,}",
                    )
                ],
                verbose_name="DOI",
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="editors",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "editor",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            ppa.pages.models.Person
                        ),
                    )
                ],
                blank=True,
                help_text="Select or create people snippets to add as editors.",
            ),
        ),
        migrations.AddField(
            model_name="editorialpage",
            name="pdf",
            field=models.URLField(
                blank=True,
                help_text="URL for a PDF of this article, if available",
                max_length=255,
                verbose_name="PDF URL",
            ),
        ),
    ]
