# Generated by Django 5.2 on 2025-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0011_alter_editorialpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocraptorSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docraptor_api_key",
                    models.CharField(
                        blank=True,
                        help_text='API Key for DocRaptor, found on your <a href="https://docraptor.com/doc_logs">DocRaptor account page</a>. Required to enable PDF generation.',
                        max_length=255,
                        verbose_name="DocRaptor API key",
                    ),
                ),
                (
                    "docraptor_limit_note",
                    models.TextField(
                        default="Limited to 5 PDFs per month.",
                        help_text="A note that will appear in the editor if the API key is present, informing users of the document limit. It is 5 per month on the free plan; edit here if plan is upgraded.",
                        verbose_name="DocRaptor limit note",
                    ),
                ),
            ],
            options={
                "verbose_name": "DocRaptor Settings",
            },
        ),
    ]
